zuul:
  sensitiveHeaders:
  host:
    socketTimeoutMillis: 10000
  routes:
    product-service:
      path: /product/**
      serviceId: product-service
eureka:
  client:
    serviceUrl:
     non-secure-port: 80
     secure-port: 443
    fetch-registry: true
    register-with-eureka: true
spring:
  cloud:
    discovery:
      enabled: true
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
  application:
    name: gateway

oauth:
  redirectUrl: http://localhost:4200/#/
  clientId: 583458414138-ve02jfni5hat2f1aqs3lpol8kv8j229t.apps.googleusercontent.com
  clientSecret: 60AXVP1AR8SF5WmYYPVgSCTf
  checkTokenUrl: https://www.googleapis.com/oauth2/v3/tokeninfo?access_token=
  userInfoUrl: https://people.googleapis.com/v1/people/me?personFields=userDefined
