zuul:
  sensitiveHeaders:
  host:
    socketTimeoutMillis: 10000
  routes:
    product-service:
      path: /product/**
      serviceId: product-service
eureka:
  client:
    serviceUrl:
     non-secure-port: 80
     secure-port: 443


